void Phase7(){
if(key=='H'||key=='h'){
Phase7=true;
  };
if(mouseButton==RIGHT){
Phase7=false;
  };
if(start==false){
Phase7=false;
  };
if(Phase3==false){
Phase7=false;
  };
if(Phase4==false){
Phase7=false;
  };
if(Phase5==false){
Phase7=false;
  };
if(Phase6==false){
Phase7=false;
  };
if(Phase7==true){
img6=loadImage("../Images/Computer-Cookies-848x480-1.jpg");
image(img6,621,0,appWidth/3,appHeight/3);
  };
};
